"use strict";
console.log("Hey Abu Hurairah, I have started learning TYPESCRIPT.");
var myname = "Muhammad Talha";
console.log("Name :" + myname);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
var diff = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
var multiply = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
var division = num10 / num2;
console.log("sum of 10 numbers is :" + sum);
console.log("Difference of 10 numbers is :" + diff);
console.log("Multiplication of 10 numbers is :" + multiply);
console.log("Division of 2 numbers 10 and 2 is :" + division);
