console.log("Hey Abu Hurairah, I have started learning TYPESCRIPT.");
var myname : string = "Muhammad Talha";
console.log("Name :"+ myname);
var num1 : number= 1;
var num2 : number= 2;
var num3 : number= 3;
var num4 : number= 4;
var num5 : number= 5;
var num6 : number= 6;
var num7 : number= 7;
var num8 : number= 8;
var num9 : number= 9;
var num10 : number=10;
var sum : number = num1+num2+num3+num4+num5+num6+num7+num8+num9+num10;
var diff : number = num1-num2-num3-num4-num5-num6-num7-num8-num9-num10;
var multiply :number =num1*num2*num3*num4*num5*num6*num7*num8*num9*num10
var division : number  = num10/num2;
console.log("sum of 10 numbers is :" + sum);
console.log("Difference of 10 numbers is :" + diff);
console.log("Multiplication of 10 numbers is :" + multiply);
console.log("Division of 2 numbers 10 and 2 is :" + division);
